#!/usr/bin/env bash
# This Script Install nginx web server
# and configures a new Ubuntu machine to respect Task requirements

apt-get update
apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

service nginx restart
