#!/usr/bin/env bash
# Install and configure HAproxy on the lb-01 server

# Check if running with root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Install HAproxy on the server
apt-get -y update
apt-get -y install haproxy

# Configure HAproxy configuration file to distribute requests
echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 64820-web-01 100.26.152.157:80
        server 64820-web-02 52.86.102.6:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy services
service haproxy restart
