#!/usr/bin/env bash
#Write a Bash script that:
#    Creates the file /var/run/myscript.pid containing its PID
#    Displays To infinity and beyond indefinitely
#    Displays I hate the kill command when receiving a SIGTERM signal
#    Displays Y U no love me?! when receiving a SIGINT signal
#    Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

pid_file="/var/run/myscript.pid"

trap 'echo "I hate the kill command";' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap 'rm -f "$pid_file"; exit;' SIGQUIT SIGTERM

echo $$ > "$pid_file"
echo "To infinity and beyond!"

while true; do
    sleep 1
done
