#!/usr/bin/env bash
#This script that displays Best School 10 times
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
a=1
while [ $a -le 100 ]; do
	if [ $((a % 5)) == 0 ] && [ $((a % 3)) == 0 ]; then
		echo "FizzBuzz"
	elif [ $((a % 3)) == 0 ]; then
		echo "Fizz"
	elif [ $((a % 5)) == 0 ]; then
		echo "Buzz"
	else
		echo $a

	fi
	((a++))
done
