#!/usr/bin/env bash
#This script displays numbers from 1 to 20 and
#displays -bad luck from China- for the 4th loop iteration
#displays -bad luck from Japan- for the 8th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration
a=1
while [ $a -le 20 ]; do
	echo $a
	if [ $((a)) == 4 ]; then
		echo "bad luck from China"
	elif [ $((a)) == 8 ]; then
		echo "bad luck from Japan"
	elif [ $((a)) == 17 ]; then
		echo "bad luck from Italy"
	fi
	((a++))
done
